function anovaTESIS_dos
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/orlando/Documents/MATLAB/spm12b/toolbox/ACL/15jul_VOL_NE.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/07/15 17:03:14

%% Initialize variables.
matlabroot= fullfile(spm('Dir'),'toolbox','ACL');
files = cellstr(spm_select('List',matlabroot,'^15jul_.*\.txt$'));
med = size(files);
for i = 1 :  med (1)
    rc2{i} = char(fullfile(matlabroot,deblank(files(i,:))))
end
% %% 
%     
% filename = '/Users/orlando/Documents/MATLAB/spm12b/toolbox/ACL/15jul_VOL_NE.txt';
% delimiter = '';
% 
% %% Format string for each line of text:
% %   column1: double (%f)
% % For more information, see the TEXTSCAN documentation.
% formatSpec = '%f%[^\n\r]';
% 
% %% Open the text file.
% fileID = fopen(filename,'r');
% 
% %% Read columns of data according to format string.
% % This call is based on the structure of the file used to generate this
% % code. If an error occurs for a different file, try regenerating the code
% % from the Import Tool.
% dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);
% 
% %% Close the text file.
% fclose(fileID);
% 
% %% Post processing for unimportable data.
% % No unimportable data rules were applied during the import, so no post
% % processing code is included. To generate code which works for
% % unimportable data, select unimportable cells in a file and regenerate the
% % script.
% 
% %% Allocate imported array to column variable names
% VarName1 = dataArray{:, 1};
% 
% %% Clear temporary variables
% clearvars filename delimiter formatSpec fileID dataArray ans;

%% 
for i = 1 :  med (1)
    Arch{i}  = importfileTESIS_dos(rc2{i});
end
Arch = Arch';

patol = importfileTESIS_dos('/Users/orlando/Documents/MATLAB/spm12b/toolbox/ACL/PATOLOGIAS.txt');

%% 
nomb_fig = {'Volumen Espacio Nativo','Cantida Espacio Nativo','Fractalidad Espacio Nativo',...
    'Intensidad Espacio Nativo','Volumen Espacio MNI','Cantida Espacio MNI','Fractalidad Espacio MNI',...
    'region1-cerebellum','region2-frontal lobe','region3-lt hemisphere','region4-occipital lobe'...
    'region5-parietal lobe','region6-rt hemisphere','region7-sub lobar','region8-temporal lobe'}
for i = 1 : med(1)
    
[P,T,STATS1,TERMS] = anovan(Arch{i},patol);
figure;
[c,m,h,nms] = multcompare(STATS1,'display','on');
title(nomb_fig{i}),xlabel('Orlando Chancay');
       [nms num2cell(m)]  
end


