%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/orlando/Documents/MATLAB/spm12b/toolbox/ACL/html/infdelessMNI_estudionuevoCANTIDAD.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/05/16 08:39:29

%% Initialize variables.
filename = '/Users/orlando/Documents/MATLAB/spm12b/toolbox/ACL/html/infdelessMNI_estudionuevoCANTIDAD.txt';
delimiter = ' ';

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: text (%s)
%	column4: double (%f)
%   column5: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%s%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
SUJETO = dataArray{:, 1};
Orlando = dataArray{:, 2};
con1 = dataArray{:, 3};
Chancay = dataArray{:, 4};
lessions = dataArray{:, 5};

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;